#include "ft_strace.h"

t_syscall *g_syscalls;

void syscalls_init(void)
{
	t_syscall syscalls[] = {{3, "read", {PARAM_NUMBER, PARAM_ADDR, PARAM_NUMBER}},
		{3, "write", {PARAM_NUMBER, PARAM_STRING, PARAM_NUMBER}},
		{3, "open", {PARAM_STRING, PARAM_NUMBER, PARAM_NUMBER}},
		{1, "close", {PARAM_NUMBER}},
		{2, "stat", {PARAM_STRING, PARAM_ADDR}},
		{2, "fstat", {PARAM_NUMBER, PARAM_ADDR}},
		{2, "lstat", {PARAM_STRING, PARAM_ADDR}},
		{3, "poll", {PARAM_ADDR, PARAM_NUMBER, PARAM_NUMBER}},
		{3, "lseek", {PARAM_NUMBER, PARAM_NUMBER, PARAM_NUMBER}},
		{6, "mmap", {PARAM_NUMBER, PARAM_NUMBER, PARAM_NUMBER, PARAM_NUMBER, PARAM_NUMBER, PARAM_NUMBER}},
		{3, "mprotect", {PARAM_NUMBER, PARAM_NUMBER, PARAM_NUMBER}},
		{2, "munmap", {PARAM_NUMBER, PARAM_NUMBER}},
		{1, "brk", {PARAM_NUMBER}},
		{4, "rt_sigaction", {PARAM_NUMBER, PARAM_ADDR, PARAM_ADDR, PARAM_NUMBER}},
		{4, "rt_sigprocmask", {PARAM_NUMBER, PARAM_ADDR, PARAM_ADDR, PARAM_NUMBER}},
		{1, "rt_sigreturn", {PARAM_NUMBER}},
		{3, "ioctl", {PARAM_NUMBER, PARAM_NUMBER, PARAM_NUMBER}},
		{4, "pread64", {PARAM_NUMBER, PARAM_ADDR, PARAM_NUMBER, PARAM_NUMBER}},
		{4, "pwrite64", {PARAM_NUMBER, PARAM_STRING, PARAM_NUMBER, PARAM_NUMBER}},
		{3, "readv", {PARAM_NUMBER, PARAM_ADDR, PARAM_NUMBER}},
		{3, "writev", {PARAM_NUMBER, PARAM_ADDR, PARAM_NUMBER}},
		{2, "access", {PARAM_STRING, PARAM_NUMBER}},
		{1, "pipe", {PARAM_ADDR}},
		{5, "select", {PARAM_NUMBER, PARAM_ADDR, PARAM_ADDR, PARAM_ADDR, PARAM_ADDR}},
		{0, "sched_yield", {}},
		{5, "mremap", {PARAM_NUMBER, PARAM_NUMBER, PARAM_NUMBER, PARAM_NUMBER, PARAM_NUMBER}},
		{3, "msync", {PARAM_NUMBER, PARAM_NUMBER, PARAM_NUMBER}},
		{3, "mincore", {PARAM_NUMBER, PARAM_NUMBER, PARAM_ADDR}},
		{3, "madvise", {PARAM_NUMBER, PARAM_NUMBER, PARAM_NUMBER}},
		{3, "shmget", {PARAM_NUMBER, PARAM_NUMBER, PARAM_NUMBER}},
		{3, "shmat", {PARAM_NUMBER, PARAM_ADDR, PARAM_NUMBER}},
		{3, "shmctl", {PARAM_NUMBER, PARAM_NUMBER, PARAM_ADDR}},
		{1, "dup", {PARAM_NUMBER}},
		{2, "dup2", {PARAM_NUMBER, PARAM_NUMBER}},
		{0, "pause", {}},
		{2, "nanosleep", {PARAM_ADDR, PARAM_ADDR}},
		{2, "getitimer", {PARAM_NUMBER, PARAM_ADDR}},
		{1, "alarm", {PARAM_NUMBER}},
		{3, "setitimer", {PARAM_NUMBER, PARAM_ADDR, PARAM_ADDR}},
		{0, "getpid", {}},
		{4, "sendfile", {PARAM_NUMBER, PARAM_NUMBER, PARAM_ADDR, PARAM_NUMBER}},
		{3, "socket", {PARAM_NUMBER, PARAM_NUMBER, PARAM_NUMBER}},
		{3, "connect", {PARAM_NUMBER, PARAM_ADDR, PARAM_NUMBER}},
		{3, "accept", {PARAM_NUMBER, PARAM_ADDR, PARAM_ADDR}},
		{6, "sendto", {PARAM_NUMBER, PARAM_ADDR, PARAM_NUMBER, PARAM_NUMBER, PARAM_ADDR, PARAM_NUMBER}},
		{6, "recvfrom", {PARAM_NUMBER, PARAM_ADDR, PARAM_NUMBER, PARAM_NUMBER, PARAM_ADDR, PARAM_ADDR}},
		{3, "sendmsg", {PARAM_NUMBER, PARAM_ADDR, PARAM_NUMBER}},
		{3, "recvmsg", {PARAM_NUMBER, PARAM_ADDR, PARAM_NUMBER}},
		{2, "shutdown", {PARAM_NUMBER, PARAM_NUMBER}},
		{3, "bind", {PARAM_NUMBER, PARAM_ADDR, PARAM_NUMBER}},
		{2, "listen", {PARAM_NUMBER, PARAM_NUMBER}},
		{3, "getsockname", {PARAM_NUMBER, PARAM_ADDR, PARAM_ADDR}},
		{3, "getpeername", {PARAM_NUMBER, PARAM_ADDR, PARAM_ADDR}},
		{4, "socketpair", {PARAM_NUMBER, PARAM_NUMBER, PARAM_NUMBER, PARAM_ADDR}},
		{5, "setsockopt", {PARAM_NUMBER, PARAM_NUMBER, PARAM_NUMBER, PARAM_ADDR, PARAM_NUMBER}},
		{5, "getsockopt", {PARAM_NUMBER, PARAM_NUMBER, PARAM_NUMBER, PARAM_ADDR, PARAM_ADDR}},
		{4, "clone", {PARAM_NUMBER, PARAM_NUMBER, PARAM_ADDR, PARAM_ADDR}},
		{0, "fork", {}},
		{0, "vfork", {}},
		{3, "execve", {PARAM_STRING, PARAM_STRING, PARAM_STRING}},
		{1, "exit", {PARAM_NUMBER}},
		{4, "wait4", {PARAM_NUMBER, PARAM_ADDR, PARAM_NUMBER, PARAM_ADDR}},
		{2, "kill", {PARAM_NUMBER, PARAM_NUMBER}},
		{1, "uname", {PARAM_ADDR}},
		{3, "semget", {PARAM_NUMBER, PARAM_NUMBER, PARAM_NUMBER}},
		{3, "semop", {PARAM_NUMBER, PARAM_ADDR, PARAM_NUMBER}},
		{4, "semctl", {PARAM_NUMBER, PARAM_NUMBER, PARAM_NUMBER, PARAM_NUMBER}},
		{1, "shmdt", {PARAM_ADDR}},
		{2, "msgget", {PARAM_NUMBER, PARAM_NUMBER}},
		{4, "msgsnd", {PARAM_NUMBER, PARAM_ADDR, PARAM_NUMBER, PARAM_NUMBER}},
		{5, "msgrcv", {PARAM_NUMBER, PARAM_ADDR, PARAM_NUMBER, PARAM_NUMBER, PARAM_NUMBER}},
		{3, "msgctl", {PARAM_NUMBER, PARAM_NUMBER, PARAM_ADDR}},
		{3, "fcntl", {PARAM_NUMBER, PARAM_NUMBER, PARAM_NUMBER}},
		{2, "flock", {PARAM_NUMBER, PARAM_NUMBER}},
		{1, "fsync", {PARAM_NUMBER}},
		{1, "fdatasync", {PARAM_NUMBER}},
		{2, "truncate", {PARAM_STRING, PARAM_NUMBER}},
		{2, "ftruncate", {PARAM_NUMBER, PARAM_NUMBER}},
		{3, "getdents", {PARAM_NUMBER, PARAM_ADDR, PARAM_NUMBER}},
		{2, "getcwd", {PARAM_ADDR, PARAM_NUMBER}},
		{1, "chdir", {PARAM_STRING}},
		{1, "fchdir", {PARAM_NUMBER}},
		{2, "rename", {PARAM_STRING, PARAM_STRING}},
		{2, "mkdir", {PARAM_STRING, PARAM_NUMBER}},
		{1, "rmdir", {PARAM_STRING}},
		{2, "creat", {PARAM_STRING, PARAM_NUMBER}},
		{2, "link", {PARAM_STRING, PARAM_STRING}},
		{1, "unlink", {PARAM_STRING}},
		{2, "symlink", {PARAM_STRING, PARAM_STRING}},
		{3, "readlink", {PARAM_STRING, PARAM_ADDR, PARAM_NUMBER}},
		{2, "chmod", {PARAM_STRING, PARAM_NUMBER}},
		{2, "fchmod", {PARAM_NUMBER, PARAM_NUMBER}},
		{3, "chown", {PARAM_STRING, PARAM_NUMBER, PARAM_NUMBER}},
		{3, "fchown", {PARAM_NUMBER, PARAM_NUMBER, PARAM_NUMBER}},
		{3, "lchown", {PARAM_STRING, PARAM_NUMBER, PARAM_NUMBER}},
		{1, "umask", {PARAM_NUMBER}},
		{2, "gettimeofday", {PARAM_ADDR, PARAM_ADDR}},
		{2, "getrlimit", {PARAM_NUMBER, PARAM_ADDR}},
		{2, "getrusage", {PARAM_NUMBER, PARAM_ADDR}},
		{1, "sysinfo", {PARAM_ADDR}},
		{1, "times", {PARAM_ADDR}},
		{4, "ptrace", {PARAM_NUMBER, PARAM_NUMBER, PARAM_NUMBER, PARAM_NUMBER}},
		{0, "getuid", {}},
		{3, "syslog", {PARAM_NUMBER, PARAM_ADDR, PARAM_NUMBER}},
		{0, "getgid", {}},
		{1, "setuid", {PARAM_NUMBER}},
		{1, "setgid", {PARAM_NUMBER}},
		{0, "geteuid", {}},
		{0, "getegid", {}},
		{2, "setpgid", {PARAM_NUMBER, PARAM_NUMBER}},
		{0, "getppid", {}},
		{0, "getpgrp", {}},
		{0, "setsid", {}},
		{2, "setreuid", {PARAM_NUMBER, PARAM_NUMBER}},
		{2, "setregid", {PARAM_NUMBER, PARAM_NUMBER}},
		{2, "getgroups", {PARAM_NUMBER, PARAM_ADDR}},
		{2, "setgroups", {PARAM_NUMBER, PARAM_ADDR}},
		{3, "setresuid", {PARAM_ADDR, PARAM_ADDR, PARAM_ADDR}},
		{3, "getresuid", {PARAM_ADDR, PARAM_ADDR, PARAM_ADDR}},
		{3, "setresgid", {PARAM_NUMBER, PARAM_NUMBER, PARAM_NUMBER}},
		{3, "getresgid", {PARAM_ADDR, PARAM_ADDR, PARAM_ADDR}},
		{1, "getpgid", {PARAM_NUMBER}},
		{1, "setfsuid", {PARAM_NUMBER}},
		{1, "setfsgid", {PARAM_NUMBER}},
		{1, "getsid", {PARAM_NUMBER}},
		{2, "capget", {PARAM_NUMBER, PARAM_NUMBER}},
		{2, "capset", {PARAM_NUMBER, PARAM_NUMBER}},
		{2, "rt_sigpending", {PARAM_ADDR, PARAM_NUMBER}},
		{4, "rt_sigtimedwait", {PARAM_ADDR, PARAM_ADDR, PARAM_ADDR, PARAM_NUMBER}},
		{3, "rt_sigqueueinfo", {PARAM_NUMBER, PARAM_NUMBER, PARAM_ADDR}},
		{2, "rt_sigsuspend", {PARAM_ADDR, PARAM_NUMBER}},
		{2, "sigaltstack", {PARAM_ADDR, PARAM_ADDR}},
		{2, "utime", {PARAM_ADDR, PARAM_ADDR}},
		{3, "mknod", {PARAM_STRING, PARAM_NUMBER, PARAM_NUMBER}},
		{1, "uselib", {PARAM_NUMBER}},
		{1, "personality", {PARAM_NUMBER}},
		{2, "ustat", {PARAM_NUMBER, PARAM_ADDR}},
		{2, "statfs", {PARAM_STRING, PARAM_ADDR}},
		{2, "fstatfs", {PARAM_NUMBER, PARAM_ADDR}},
		{3, "sysfs", {PARAM_NUMBER, PARAM_NUMBER, PARAM_NUMBER}},
		{2, "getpriority", {PARAM_NUMBER, PARAM_NUMBER}},
		{3, "setpriority", {PARAM_NUMBER, PARAM_NUMBER, PARAM_NUMBER}},
		{2, "sched_setparam", {PARAM_NUMBER, PARAM_ADDR}},
		{2, "sched_getparam", {PARAM_NUMBER, PARAM_ADDR}},
		{3, "sched_setscheduler", {PARAM_NUMBER, PARAM_NUMBER, PARAM_ADDR}},
		{1, "sched_getscheduler", {PARAM_NUMBER}},
		{1, "sched_get_priority_max", {PARAM_NUMBER}},
		{1, "sched_get_priority_min", {PARAM_NUMBER}},
		{2, "sched_rr_get_interval", {PARAM_NUMBER, PARAM_ADDR}},
		{2, "mlock", {PARAM_NUMBER, PARAM_NUMBER}},
		{2, "munlock", {PARAM_NUMBER, PARAM_NUMBER}},
		{1, "mlockall", {PARAM_NUMBER}},
		{0, "munlockall", {}},
		{0, "vhangup", {}},
		{3, "modify_ldt", {PARAM_NUMBER, PARAM_ADDR, PARAM_NUMBER}},
		{2, "pivot_root", {PARAM_STRING, PARAM_STRING}},
		{1, "_sysctl", {PARAM_ADDR}},
		{5, "prctl", {PARAM_NUMBER, PARAM_NUMBER, PARAM_NUMBER, PARAM_NUMBER, PARAM_NUMBER}},
		{3, "arch_prctl", {PARAM_ADDR, PARAM_NUMBER, PARAM_ADDR}},
		{1, "adjtimex", {PARAM_ADDR}},
		{2, "setrlimit", {PARAM_NUMBER, PARAM_ADDR}},
		{1, "chroot", {PARAM_STRING}},
		{0, "sync", {}},
		{1, "acct", {PARAM_STRING}},
		{2, "settimeofday", {PARAM_ADDR, PARAM_ADDR}},
		{5, "mount", {PARAM_ADDR, PARAM_ADDR, PARAM_ADDR, PARAM_NUMBER, PARAM_ADDR}},
		{2, "umount2", {PARAM_STRING, PARAM_NUMBER}},
		{2, "swapon", {PARAM_STRING, PARAM_NUMBER}},
		{1, "swapoff", {PARAM_STRING}},
		{4, "reboot", {PARAM_NUMBER, PARAM_NUMBER, PARAM_NUMBER, PARAM_ADDR}},
		{2, "sethostname", {PARAM_ADDR, PARAM_NUMBER}},
		{2, "setdomainname", {PARAM_ADDR, PARAM_NUMBER}},
		{2, "iopl", {PARAM_NUMBER, PARAM_ADDR}},
		{3, "ioperm", {PARAM_NUMBER, PARAM_NUMBER, PARAM_NUMBER}},
		{1, "create_module", {PARAM_NUMBER}},
		{3, "init_module", {PARAM_ADDR, PARAM_NUMBER, PARAM_STRING}},
		{2, "delete_module", {PARAM_ADDR, PARAM_NUMBER}},
		{1, "get_kernel_syms", {PARAM_NUMBER}},
		{1, "query_module", {PARAM_NUMBER}},
		{4, "quotactl", {PARAM_NUMBER, PARAM_STRING, PARAM_NUMBER, PARAM_ADDR}},
		{1, "nfsservctl", {PARAM_NUMBER}},
		{1, "getpmsg", {PARAM_NUMBER}},
		{1, "putpmsg", {PARAM_NUMBER}},
		{1, "afs_syscall", {PARAM_NUMBER}},
		{1, "tuxcall", {PARAM_NUMBER}},
		{1, "security", {PARAM_NUMBER}},
		{0, "gettid", {}},
		{3, "readahead", {PARAM_NUMBER, PARAM_NUMBER, PARAM_NUMBER}},
		{5, "setxattr", {PARAM_STRING, PARAM_STRING, PARAM_ADDR, PARAM_NUMBER, PARAM_NUMBER}},
		{5, "lsetxattr", {PARAM_STRING, PARAM_STRING, PARAM_ADDR, PARAM_NUMBER, PARAM_NUMBER}},
		{5, "fsetxattr", {PARAM_NUMBER, PARAM_STRING, PARAM_ADDR, PARAM_NUMBER, PARAM_NUMBER}},
		{4, "getxattr", {PARAM_STRING, PARAM_STRING, PARAM_ADDR, PARAM_NUMBER}},
		{4, "lgetxattr", {PARAM_STRING, PARAM_STRING, PARAM_ADDR, PARAM_NUMBER}},
		{4, "fgetxattr", {PARAM_NUMBER, PARAM_ADDR, PARAM_ADDR, PARAM_NUMBER}},
		{3, "listxattr", {PARAM_STRING, PARAM_ADDR, PARAM_NUMBER}},
		{3, "llistxattr", {PARAM_STRING, PARAM_ADDR, PARAM_NUMBER}},
		{3, "flistxattr", {PARAM_NUMBER, PARAM_ADDR, PARAM_NUMBER}},
		{2, "removexattr", {PARAM_STRING, PARAM_STRING}},
		{2, "lremovexattr", {PARAM_STRING, PARAM_STRING}},
		{2, "fremovexattr", {PARAM_NUMBER, PARAM_STRING}},
		{2, "tkill", {PARAM_NUMBER, PARAM_NUMBER}},
		{1, "time", {PARAM_ADDR}},
		{6, "futex", {PARAM_ADDR, PARAM_NUMBER, PARAM_NUMBER, PARAM_ADDR, PARAM_ADDR, PARAM_NUMBER}},
		{3, "sched_setaffinity", {PARAM_NUMBER, PARAM_NUMBER, PARAM_ADDR}},
		{3, "sched_getaffinity", {PARAM_NUMBER, PARAM_NUMBER, PARAM_ADDR}},
		{1, "set_thread_area", {PARAM_NUMBER}},
		{2, "io_setup", {PARAM_NUMBER, PARAM_ADDR}},
		{1, "io_destroy", {PARAM_NUMBER}},
		{4, "io_getevents", {PARAM_NUMBER, PARAM_NUMBER, PARAM_NUMBER, PARAM_ADDR}},
		{3, "io_submit", {PARAM_NUMBER, PARAM_NUMBER, PARAM_ADDR}},
		{3, "io_cancel", {PARAM_NUMBER, PARAM_ADDR, PARAM_ADDR}},
		{1, "get_thread_area", {PARAM_NUMBER}},
		{3, "lookup_dcookie", {PARAM_NUMBER, PARAM_NUMBER, PARAM_NUMBER}},
		{1, "epoll_create", {PARAM_NUMBER}},
		{1, "epoll_ctl_old", {PARAM_NUMBER}},
		{1, "epoll_wait_old", {PARAM_NUMBER}},
		{5, "remap_file_pages", {PARAM_NUMBER, PARAM_NUMBER, PARAM_NUMBER, PARAM_NUMBER, PARAM_NUMBER}},
		{3, "getdents64", {PARAM_NUMBER, PARAM_ADDR, PARAM_NUMBER}},
		{1, "set_tid_address", {PARAM_ADDR}},
		{0, "restart_syscall", {}},
		{4, "semtimedop", {PARAM_NUMBER, PARAM_ADDR, PARAM_NUMBER, PARAM_ADDR}},
		{4, "fadvise64", {PARAM_NUMBER, PARAM_NUMBER, PARAM_NUMBER, PARAM_NUMBER}},
		{3, "timer_create", {PARAM_NUMBER, PARAM_ADDR, PARAM_ADDR}},
		{4, "timer_settime", {PARAM_NUMBER, PARAM_NUMBER, PARAM_ADDR, PARAM_ADDR}},
		{2, "timer_gettime", {PARAM_NUMBER, PARAM_ADDR}},
		{1, "timer_getoverrun", {PARAM_NUMBER}},
		{1, "timer_delete", {PARAM_NUMBER}},
		{2, "clock_settime", {PARAM_NUMBER, PARAM_ADDR}},
		{2, "clock_gettime", {PARAM_NUMBER, PARAM_ADDR}},
		{2, "clock_getres", {PARAM_NUMBER, PARAM_ADDR}},
		{4, "clock_nanosleep", {PARAM_NUMBER, PARAM_NUMBER, PARAM_ADDR, PARAM_ADDR}},
		{1, "exit_group", {PARAM_NUMBER}},
		{4, "epoll_wait", {PARAM_NUMBER, PARAM_ADDR, PARAM_NUMBER, PARAM_NUMBER}},
		{4, "epoll_ctl", {PARAM_NUMBER, PARAM_NUMBER, PARAM_NUMBER, PARAM_ADDR}},
		{3, "tgkill", {PARAM_NUMBER, PARAM_NUMBER, PARAM_NUMBER}},
		{2, "utimes", {PARAM_ADDR, PARAM_ADDR}},
		{1, "vserver", {PARAM_NUMBER}},
		{6, "mbind", {PARAM_NUMBER, PARAM_NUMBER, PARAM_NUMBER, PARAM_ADDR, PARAM_NUMBER, PARAM_NUMBER}},
		{3, "set_mempolicy", {PARAM_NUMBER, PARAM_ADDR, PARAM_NUMBER}},
		{5, "get_mempolicy", {PARAM_ADDR, PARAM_ADDR, PARAM_NUMBER, PARAM_NUMBER, PARAM_NUMBER}},
		{4, "mq_open", {PARAM_STRING, PARAM_NUMBER, PARAM_NUMBER, PARAM_ADDR}},
		{1, "mq_unlink", {PARAM_STRING}},
		{5, "mq_timedsend", {PARAM_NUMBER, PARAM_STRING, PARAM_NUMBER, PARAM_NUMBER, PARAM_ADDR}},
		{5, "mq_timedreceive", {PARAM_NUMBER, PARAM_ADDR, PARAM_NUMBER, PARAM_ADDR, PARAM_ADDR}},
		{2, "mq_notify", {PARAM_NUMBER, PARAM_ADDR}},
		{3, "mq_getsetattr", {PARAM_NUMBER, PARAM_ADDR, PARAM_ADDR}},
		{4, "kexec_load", {PARAM_NUMBER, PARAM_NUMBER, PARAM_ADDR, PARAM_NUMBER}},
		{5, "waitid", {PARAM_NUMBER, PARAM_NUMBER, PARAM_ADDR, PARAM_NUMBER, PARAM_ADDR}},
		{4, "add_key", {PARAM_STRING, PARAM_STRING, PARAM_ADDR, PARAM_NUMBER}},
		{4, "request_key", {PARAM_STRING, PARAM_STRING, PARAM_STRING, PARAM_NUMBER}},
		{5, "keyctl", {PARAM_NUMBER, PARAM_NUMBER, PARAM_NUMBER, PARAM_NUMBER, PARAM_NUMBER}},
		{3, "ioprio_set", {PARAM_NUMBER, PARAM_NUMBER, PARAM_NUMBER}},
		{2, "ioprio_get", {PARAM_NUMBER, PARAM_NUMBER}},
		{0, "inotify_init", {}},
		{3, "inotify_add_watch", {PARAM_NUMBER, PARAM_STRING, PARAM_NUMBER}},
		{2, "inotify_rm_watch", {PARAM_NUMBER, PARAM_NUMBER}},
		{4, "migrate_pages", {PARAM_NUMBER, PARAM_NUMBER, PARAM_ADDR, PARAM_ADDR}},
		{4, "openat", {PARAM_NUMBER, PARAM_STRING, PARAM_NUMBER, PARAM_NUMBER}},
		{3, "mkdirat", {PARAM_NUMBER, PARAM_STRING, PARAM_NUMBER}},
		{4, "mknodat", {PARAM_NUMBER, PARAM_STRING, PARAM_NUMBER, PARAM_NUMBER}},
		{5, "fchownat", {PARAM_NUMBER, PARAM_STRING, PARAM_NUMBER, PARAM_NUMBER, PARAM_NUMBER}},
		{3, "futimesat", {PARAM_NUMBER, PARAM_STRING, PARAM_ADDR}},
		{4, "newfstatat", {PARAM_NUMBER, PARAM_STRING, PARAM_ADDR, PARAM_NUMBER}},
		{3, "unlinkat", {PARAM_NUMBER, PARAM_STRING, PARAM_NUMBER}},
		{4, "renameat", {PARAM_NUMBER, PARAM_STRING, PARAM_NUMBER, PARAM_STRING}},
		{5, "linkat", {PARAM_NUMBER, PARAM_STRING, PARAM_NUMBER, PARAM_STRING, PARAM_NUMBER}},
		{3, "symlinkat", {PARAM_STRING, PARAM_NUMBER, PARAM_STRING}},
		{4, "readlinkat", {PARAM_NUMBER, PARAM_STRING, PARAM_ADDR, PARAM_NUMBER}},
		{3, "fchmodat", {PARAM_NUMBER, PARAM_STRING, PARAM_NUMBER}},
		{3, "faccessat", {PARAM_NUMBER, PARAM_STRING, PARAM_NUMBER}},
		{6, "pselect6", {PARAM_NUMBER, PARAM_ADDR, PARAM_ADDR, PARAM_ADDR, PARAM_ADDR, PARAM_ADDR}},
		{5, "ppoll", {PARAM_ADDR, PARAM_NUMBER, PARAM_ADDR, PARAM_ADDR, PARAM_NUMBER}},
		{1, "unshare", {PARAM_NUMBER}},
		{2, "set_robust_list", {PARAM_ADDR, PARAM_NUMBER}},
		{3, "get_robust_list", {PARAM_NUMBER, PARAM_ADDR, PARAM_ADDR}},
		{6, "splice", {PARAM_NUMBER, PARAM_ADDR, PARAM_NUMBER, PARAM_ADDR, PARAM_NUMBER, PARAM_NUMBER}},
		{4, "tee", {PARAM_NUMBER, PARAM_NUMBER, PARAM_NUMBER, PARAM_NUMBER}},
		{4, "sync_file_range", {PARAM_NUMBER, PARAM_NUMBER, PARAM_NUMBER, PARAM_NUMBER}},
		{4, "vmsplice", {PARAM_NUMBER, PARAM_ADDR, PARAM_NUMBER, PARAM_NUMBER}},
		{6, "move_pages", {PARAM_NUMBER, PARAM_NUMBER, PARAM_ADDR, PARAM_ADDR, PARAM_ADDR, PARAM_NUMBER}},
		{4, "utimensat", {PARAM_NUMBER, PARAM_STRING, PARAM_ADDR, PARAM_NUMBER}},
		{6, "epoll_pwait", {PARAM_NUMBER, PARAM_ADDR, PARAM_NUMBER, PARAM_NUMBER, PARAM_ADDR, PARAM_NUMBER}},
		{3, "signalfd", {PARAM_NUMBER, PARAM_ADDR, PARAM_NUMBER}},
		{2, "timerfd_create", {PARAM_NUMBER, PARAM_NUMBER}},
		{1, "eventfd", {PARAM_NUMBER}},
		{4, "fallocate", {PARAM_NUMBER, PARAM_NUMBER, PARAM_NUMBER, PARAM_NUMBER}},
		{4, "timerfd_settime", {PARAM_NUMBER, PARAM_NUMBER, PARAM_ADDR, PARAM_ADDR}},
		{2, "timerfd_gettime", {PARAM_NUMBER, PARAM_ADDR}},
		{4, "accept4", {PARAM_NUMBER, PARAM_ADDR, PARAM_ADDR, PARAM_NUMBER}},
		{4, "signalfd4", {PARAM_NUMBER, PARAM_ADDR, PARAM_NUMBER, PARAM_NUMBER}},
		{2, "eventfd2", {PARAM_NUMBER, PARAM_NUMBER}},
		{1, "epoll_create1", {PARAM_NUMBER}},
		{3, "dup3", {PARAM_NUMBER, PARAM_NUMBER, PARAM_NUMBER}},
		{2, "pipe2", {PARAM_ADDR, PARAM_NUMBER}},
		{1, "inotify_init1", {PARAM_NUMBER}},
		{5, "preadv", {PARAM_NUMBER, PARAM_ADDR, PARAM_NUMBER, PARAM_NUMBER, PARAM_NUMBER}},
		{5, "pwritev", {PARAM_NUMBER, PARAM_ADDR, PARAM_NUMBER, PARAM_NUMBER, PARAM_NUMBER}},
		{4, "rt_tgsigqueueinfo", {PARAM_NUMBER, PARAM_NUMBER, PARAM_NUMBER, PARAM_ADDR}},
		{5, "perf_event_open", {PARAM_ADDR, PARAM_NUMBER, PARAM_NUMBER, PARAM_NUMBER, PARAM_NUMBER}},
		{5, "recvmmsg", {PARAM_NUMBER, PARAM_ADDR, PARAM_NUMBER, PARAM_NUMBER, PARAM_ADDR}},
		{2, "fanotify_init", {PARAM_NUMBER, PARAM_NUMBER}},
		{5, "fanotify_mark", {PARAM_NUMBER, PARAM_NUMBER, PARAM_NUMBER, PARAM_NUMBER, PARAM_NUMBER}},
		{4, "prlimit64", {PARAM_NUMBER, PARAM_NUMBER, PARAM_ADDR, PARAM_ADDR}},
		{5, "name_to_handle_at", {PARAM_NUMBER, PARAM_STRING, PARAM_ADDR, PARAM_ADDR, PARAM_NUMBER}},
		{5, "open_by_handle_at", {PARAM_NUMBER, PARAM_STRING, PARAM_ADDR, PARAM_ADDR, PARAM_NUMBER}},
		{2, "clock_adjtime", {PARAM_NUMBER, PARAM_ADDR}},
		{1, "syncfs", {PARAM_NUMBER}},
		{4, "sendmmsg", {PARAM_NUMBER, PARAM_ADDR, PARAM_NUMBER, PARAM_NUMBER}},
		{2, "setns", {PARAM_NUMBER, PARAM_NUMBER}},
		{3, "getcpu", {PARAM_ADDR, PARAM_ADDR, PARAM_ADDR}},
		{6, "process_vm_readv", {PARAM_NUMBER, PARAM_ADDR, PARAM_NUMBER, PARAM_ADDR, PARAM_NUMBER, PARAM_NUMBER}},
		{6, "process_vm_writev", {PARAM_NUMBER, PARAM_ADDR, PARAM_NUMBER, PARAM_ADDR, PARAM_NUMBER, PARAM_NUMBER}},
		{5, "kcmp", {PARAM_NUMBER, PARAM_NUMBER, PARAM_NUMBER, PARAM_NUMBER, PARAM_NUMBER}},
		{3, "finit_module", {PARAM_NUMBER, PARAM_STRING, PARAM_NUMBER}},
		{3, "sched_setattr", {PARAM_NUMBER, PARAM_ADDR, PARAM_NUMBER}},
		{4, "sched_getattr", {PARAM_NUMBER, PARAM_ADDR, PARAM_NUMBER, PARAM_NUMBER}},
		{5, "renameat2", {PARAM_NUMBER, PARAM_STRING, PARAM_NUMBER, PARAM_STRING, PARAM_NUMBER}},
		{3, "seccomp", {PARAM_NUMBER, PARAM_NUMBER, PARAM_STRING}},
		{3, "getrandom", {PARAM_ADDR, PARAM_NUMBER, PARAM_NUMBER}},
		{2, "memfd_create", {PARAM_STRING, PARAM_NUMBER}},
		{5, "kexec_file_load", {PARAM_NUMBER, PARAM_NUMBER, PARAM_NUMBER, PARAM_STRING, PARAM_NUMBER}},
		{3, "bpf", {PARAM_NUMBER, PARAM_ADDR, PARAM_NUMBER}},
		{5, "stub_execveat", {PARAM_NUMBER, PARAM_STRING, PARAM_ADDR, PARAM_ADDR, PARAM_NUMBER}},
		{1, "userfaultfd", {PARAM_NUMBER}},
		{2, "membarrier", {PARAM_NUMBER, PARAM_NUMBER}},
		{3, "mlock2", {PARAM_NUMBER, PARAM_NUMBER, PARAM_NUMBER}},
		{6, "copy_file_range", {PARAM_NUMBER, PARAM_ADDR, PARAM_NUMBER, PARAM_ADDR, PARAM_NUMBER, PARAM_NUMBER}},
		{6, "preadv2", {PARAM_NUMBER, PARAM_ADDR, PARAM_NUMBER, PARAM_NUMBER, PARAM_NUMBER, PARAM_NUMBER}},
		{6, "pwritev2", {PARAM_NUMBER, PARAM_ADDR, PARAM_NUMBER, PARAM_NUMBER, PARAM_NUMBER, PARAM_NUMBER}}};
  /*	t_syscall syscalls[] = {{3,"read"},
		{3,"write"},
		{3,"open"},
		{1,"close"},
		{2,"stat"},
		{2,"fstat"},
		{2,"lstat"},
		{3,"poll"},
		{3,"lseek"},
		{6,"mmap"},
		{3,"mprotect"},
		{2,"munmap"},
		{1,"brk"},
		{4,"rt_sigaction"},
		{4,"rt_sigprocmask"},
		{0,"rt_sigreturn"},
		{3,"ioctl"},
		{4,"pread"},
		{4,"pwrite"},
		{3,"readv"},
		{3,"writev"},
		{2,"access"},
		{1,"pipe"},
		{5,"select"},
		{0,"sched_yield"},
		{5,"mremap"},
		{3,"msync"},
		{3,"mincore"},
		{3,"madvise"},
		{4,"shmget"},
		{4,"shmat"},
		{4,"shmctl"},
		{1,"dup"},
		{2,"dup2"},
		{0,"pause"},
		{2,"nanosleep"},
		{2,"getitimer"},
		{1,"alarm"},
		{3,"setitimer"},
		{0,"getpid"},
		{4,"sendfile"},
		{3,"socket"},
		{3,"connect"},
		{3,"accept"},
		{6,"sendto"},
		{6,"recvfrom"},
		{3,"sendmsg"},
		{3,"recvmsg"},
		{2,"shutdown"},
		{3,"bind"},
		{2,"listen"},
		{3,"getsockname"},
		{3,"getpeername"},
		{4,"socketpair"},
		{5,"setsockopt"},
		{5,"getsockopt"},
		{5,"clone"},
		{0,"fork"},
		{0,"vfork"},
		{3,"execve"},
		{1,"_exit"},
		{4,"wait4"},
		{2,"kill"},
		{1,"uname"},
		{4,"semget"},
		{4,"semop"},
		{4,"semctl"},
		{4,"shmdt"},
		{4,"msgget"},
		{4,"msgsnd"},
		{5,"msgrcv"},
		{3,"msgctl"},
		{3,"fcntl"},
		{2,"flock"},
		{1,"fsync"},
		{1,"fdatasync"},
		{2,"truncate"},
		{2,"ftruncate"},
		{3,"getdents"},
		{2,"getcwd"},
		{1,"chdir"},
		{1,"fchdir"},
		{2,"rename"},
		{2,"mkdir"},
		{1,"rmdir"},
		{2,"creat"},
		{2,"link"},
		{1,"unlink"},
		{2,"symlink"},
		{3,"readlink"},
		{2,"chmod"},
		{2,"fchmod"},
		{3,"chown"},
		{3,"fchown"},
		{3,"lchown"},
		{1,"umask"},
		{2,"gettimeofday"},
		{2,"getrlimit"},
		{2,"getrusage"},
		{1,"sysinfo"},
		{1,"times"},
		{4,"ptrace"},
		{0,"getuid"},
		{3,"syslog"},
		{0,"getgid"},
		{1,"setuid"},
		{1,"setgid"},
		{0,"geteuid"},
		{0,"getegid"},
		{2,"setpgid"},
		{0,"getppid"},
		{0,"getpgrp"},
		{0,"setsid"},
		{2,"setreuid"},
		{2,"setregid"},
		{2,"getgroups"},
		{2,"setgroups"},
		{3,"setresuid"},
		{3,"getresuid"},
		{3,"setresgid"},
		{3,"getresgid"},
		{1,"getpgid"},
		{1,"setfsuid"},
		{1,"setfsgid"},
		{1,"getsid"},
		{2,"capget"},
		{2,"capset"},
		{2,"rt_sigpending"},
		{4,"rt_sigtimedwait"},
		{3,"rt_sigqueueinfo"},
		{2,"rt_sigsuspend"},
		{2,"sigaltstack"},
		{2,"utime"},
		{3,"mknod"},
		{1,"uselib"},
		{1,"personality"},
		{2,"ustat"},
		{2,"statfs"},
		{2,"fstatfs"},
		{3,"sysfs"},
		{2,"getpriority"},
		{3,"setpriority"},
		{0,"sched_setparam"},
		{2,"sched_getparam"},
		{3,"sched_setscheduler"},
		{1,"sched_getscheduler"},
		{1,"sched_get_priority_max"},
		{1,"sched_get_priority_min"},
		{2,"sched_rr_get_interval"},
		{2,"mlock"},
		{2,"munlock"},
		{1,"mlockall"},
		{0,"munlockall"},
		{0,"vhangup"},
		{3,"modify_ldt"},
		{2,"pivot_root"},
		{1,"_sysctl"},
		{5,"prctl"},
		{2,"arch_prctl"},
		{1,"adjtimex"},
		{2,"setrlimit"},
		{1,"chroot"},
		{0,"sync"},
		{1,"acct"},
		{2,"settimeofday"},
		{5,"mount"},
		{2,"umount"},
		{2,"swapon"},
		{1,"swapoff"},
		{4,"reboot"},
		{2,"sethostname"},
		{2,"setdomainname"},
		{1,"iopl"},
		{3,"ioperm"},
		{2,"create_module"},
		{3,"init_module"},
		{2,"delete_module"},
		{1,"get_kernel_syms"},
		{5,"query_module"},
		{4,"quotactl"},
		{3,"nfsservctl"},
		{5,"getpmsg"},
		{5,"putpmsg"},
		{5,"afs_syscall"},
		{3,"tuxcall"},
		{3,"security"},
		{0,"gettid"},
		{3,"readahead"},
		{5,"setxattr"},
		{5,"lsetxattr"},
		{5,"fsetxattr"},
		{4,"getxattr"},
		{4,"lgetxattr"},
		{4,"fgetxattr"},
		{3,"listxattr"},
		{3,"llistxattr"},
		{3,"flistxattr"},
		{2,"removexattr"},
		{2,"lremovexattr"},
		{2,"fremovexattr"},
		{2,"tkill"},
		{1,"time"},
		{6,"futex"},
		{3,"sched_setaffinity"},
		{3,"sched_getaffinity"},
		{1,"set_thread_area"},
		{2,"io_setup"},
		{1,"io_destroy"},
		{5,"io_getevents"},
		{3,"io_submit"},
		{3,"io_cancel"},
		{1,"get_thread_area"},
		{3,"lookup_dcookie"},
		{1,"epoll_create"},
		{4,"epoll_ctl_old"},
		{4,"epoll_wait_old"},
		{5,"remap_file_pages"},
		{3,"getdents64"},
		{1,"set_tid_address"},
		{0,"restart_syscall"},
		{5,"semtimedop"},
		{4,"fadvise64"},
		{3,"timer_create"},
		{4,"timer_settime"},
		{2,"timer_gettime"},
		{1,"timer_getoverrun"},
		{1,"timer_delete"},
		{2,"clock_settime"},
		{2,"clock_gettime"},
		{2,"clock_getres"},
		{4,"clock_nanosleep"},
		{1,"exit_group"},
		{4,"epoll_wait"},
		{4,"epoll_ctl"},
		{3,"tgkill"},
		{2,"utimes"},
		{5,"vserver"},
		{6,"mbind"},
		{3,"set_mempolicy"},
		{5,"get_mempolicy"},
		{4,"mq_open"},
		{1,"mq_unlink"},
		{5,"mq_timedsend"},
		{5,"mq_timedreceive"},
		{2,"mq_notify"},
		{3,"mq_getsetattr"},
		{4,"kexec_load"},
		{5,"waitid"},
		{5,"add_key"},
		{4,"request_key"},
		{5,"keyctl"},
		{3,"ioprio_set"},
		{2,"ioprio_get"},
		{0,"inotify_init"},
		{3,"inotify_add_watch"},
		{2,"inotify_rm_watch"},
		{4,"migrate_pages"},
		{4,"openat"},
		{3,"mkdirat"},
		{4,"mknodat"},
		{5,"fchownat"},
		{3,"futimesat"},
		{4,"newfstatat"},
		{3,"unlinkat"},
		{4,"renameat"},
		{5,"linkat"},
		{3,"symlinkat"},
		{4,"readlinkat"},
		{3,"fchmodat"},
		{3,"faccessat"},
		{6,"pselect6"},
		{5,"ppoll"},
		{1,"unshare"},
		{2,"set_robust_list"},
		{3,"get_robust_list"},
		{6,"splice"},
		{4,"tee"},
		{4,"sync_file_range"},
		{4,"vmsplice"},
		{6,"move_pages"},
		{4,"utimensat"},
		{6,"epoll_pwait"},
		{3,"signalfd"},
		{2,"timerfd_create"},
		{1,"eventfd"},
		{4,"fallocate"},
		{4,"timerfd_settime"},
		{2,"timerfd_gettime"},
		{4,"accept4"},
		{4,"signalfd4"},
		{2,"eventfd2"},
		{1,"epoll_create1"},
		{3,"dup3"},
		{2,"pipe2"},
		{1,"inotify_init1"},
		{4,"preadv"},
		{4,"pwritev"},
		{4,"rt_tgsigqueueinfo"},
		{5,"perf_event_open"},
		{5,"recvmmsg"},
		{2,"fanotify_init"},
		{5,"fanotify_mark"},
		{4,"prlimit64"},
		{5,"name_to_handle_at"},
		{3,"open_by_handle_at"},
		{2,"clock_adjtime"},
		{1,"syncfs"},
		{4,"sendmmsg"},
		{2,"setns"},
		{3,"getcpu"},
		{6,"process_vm_readv"},
		{6,"process_vm_writev"},
		{5,"kcmp"},
		{3,"finit_module"}};*/
    if (!(g_syscalls = malloc(sizeof(syscalls))))
    {
      	ft_putendl_fd("ft_strace: can't malloc syscalls names", 2);
      	exit(EXIT_FAILURE);
    }
    ft_memcpy(g_syscalls, syscalls, sizeof(syscalls));
}
